# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: d73a4a
    description: Something is not working

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: duplicate
    color: cfd3d7
    descrption: This issue or pull request already exists

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: wontfix
    color: ffffff
    description: This will not be worked on

  - name: stale
    color: a0a0a0
    description: This issue or pull request has been marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
      required_status_checks:
        strict: true
        contexts:
          - Link Check
          - CodeSpell
          - Markdown Linter
      enforce_admins: false
      required_linear_history: true
