name: Publish
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout repository
      uses: actions/checkout@v3
      
    - id: setup_node
      name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - id: install_deps
      name: Install Dependencies
      run: npm ci
      
    - id: build
      name: Build
      run: npm run build
      
    - id: do_tests
      name: Unit Tests
      run: npm test
  
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test
    steps:
    - id: checkout
      name: Checkout repository
      uses: actions/checkout@v3
      
    - id: setup_node
      name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - id: install_deps
      name: Install Dependencies
      run: npm ci
      
    - id: build
      name: Build
      run: npm run build

    - id: publish_npm
      name: Publish to NPM Registry
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Fail
      if: steps.publish_npm.outputs.type != 'none'
      run: exit 1

  publish-gh:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: test
    steps:
    - id: checkout
      name: Checkout repository
      uses: actions/checkout@v3
      
    - id: setup_node
      name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - id: install_deps
      name: Install Dependencies
      run: npm ci
      
    - id: build
      name: Build
      run: npm run build

    - id: publish_gh
      name: Publish to GitHub Registry
      uses: JS-DevTools/npm-publish@v1
      with:
        registry: https://npm.pkg.github.com
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fail
      if: steps.publish_gh.outputs.type != 'none'
      run: exit 1
      
  release:
    name: Create Release
    needs: [ publish-npm, publish-gh ]
    runs-on: ubuntu-latest
    steps:
    - id: create_release
      name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.publish_npm.outputs.version }}
        release_name: Release ${{ steps.publish_npm.outputs.version }}
        body: ${{ steps.publish_npm.outputs.version }}
        draft: false
        prerelease: false
